import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppThemeProvider from "@/components/providers/ThemeProvider";
import "./globals.css";
import Container from "@/components/layout/Container";
import { colors } from "@/lib/colors";
import Header from "@/components/layout/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{
      ["--color-primary" as any]: colors.primary,
    }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppThemeProvider>
          <Container>
            <Header />
          </Container>
          {children}
        </AppThemeProvider>
      </body>
    </html>
  );
}
